[package]
name = "filtration-domination"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.0"
sorted-iter = "0.1.8"
rand = "0.8.5"
litemap = "0.3.0"
rustc-hash = "1.1.0"
nohash-hasher = "0.2.0"