[package]
name = "filtration_domination"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
num = "0.4.0"
sorted-iter = "0.1.8"
rand = "0.8.5"
litemap = "0.3.0"
rustc-hash = "1.1.0"